project:
  type: website

website:
  title: "Elizaveta Kugaevskaia"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about/index.qmd
        text: About

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



