project:
  type: website

website:
  title: "Elizaveta Kugaevskaia"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about/index.qmd
        text: About
      - href: https://elisacoffee.github.io/cv/cv.pdf
        text: CV

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



