project:
  type: website

website:
  title: "Elizaveta Kugaevskaia"
  favicon: static/img/coffee-beans-filled-roast-brew.svg
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about/index.qmd
        text: About
    #  - href: https://elisacoffee.github.io/cv/cv.pdf
    #    text: CV

format:
  html:
    theme: static/html/custom.scss
    toc: true



